name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: Production
            url: https://markshify.theprinceraj.tech
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{secrets.EC2_SSH_PEM_KEY}}
                  script: |
                      cd ~/Markshify
                      git pull origin main
                      bun install
                      pm2 restart markshify
